spring:
  datasource:
    url: jdbc:postgresql://cd5vlri6nnqe17.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d92pgdm04s1k2s
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  cache:
    type: redis
  data:
    redis:
      host: redis-17848.c281.us-east-1-2.ec2.redns.redis-cloud.com
      port: 17848
      password: ${REDISCLOUD_PASSWORD}
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${API_SECRET}
