create table course(
    id bigint generated by default as identity not null,
    name varchar(50),
    category varchar(50),
    constraint pk_course primary key(id)
);

insert into course (id, name, category) values (1, 'Kotlin', 'OOP');
insert into course (id, name, category) values (2, 'Kotlin', 'WEB');
insert into course (id, name, category) values (3, 'Go', 'OOP');