create table topic(
    id bigint generated by default as identity not null,
    title varchar(50) not null,
    message varchar(300) not null,
    created_at timestamp without time zone not null,
    topic_status varchar(20) not null,
    course_id bigint not null,
    author_id bigint not null,
    constraint pk_topic primary key(id),
    constraint fk_topic_on_course foreign key(course_id) references course(id),
    constraint fk_topic_on_author foreign key(author_id) references forum_user(id)
);

insert into topic(id, title, message, created_at, topic_status, course_id, author_id)
values(1, 'Kotlin doubt', 'My let function does not work...', '2021-12-24 12:00:00', 'NOT_ANSWERED', 1, 1);