create table answer(
    id bigint generated by default as identity not null,
    message varchar(300) not null,
    created_at timestamp without time zone not null,
    topic_id bigint not null,
    author_id bigint not null,
    solution boolean not null,
    constraint pk_answer primary key(id),
    constraint fk_answer_on_topic foreign key (topic_id) references topic(id),
    constraint fk_answer_on_author foreign key (author_id) references forum_user(id)
);
