create table user_role (
    id bigint generated by default as identity not null,
    forum_user_id bigint not null,
    role_id bigint not null,
    constraint pk_user_role primary key(id),
    constraint fk_user_role_on_forum_user foreign key(forum_user_id) references forum_user(id),
    constraint fk_user_role_on_role foreign key(role_id) references role(id)
);

insert into user_role (id, forum_user_id, role_id) VALUES (1, 1, 1);